name: Build, Push, Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  call-workflow:
    name: Centralized workflow
    uses: flighttrackr/workflows/.github/workflows/release.yml@main
    with:
      hub_repo: flighttrackr
      hub_image: pfclient
      image_authors: Dennis Neufeld <git@dneufeld.net>
      image_title: pfclient
      image_description: Dockerized Plane Finder Client (pfclient)
      image_licenses: MIT
